#Config for Villager In A Bucket
#'enable-zombie-villager' should the ability to pick up Zombie Villagers in buckets be enabled. Default true
#'harm-reputation' controls whether the reputation of the picked up villager should be harmed (Equal to punching it)
#
#Mon Feb 23 13:39:37 PKT 2026
enable-zombie-villager=true
harm-reputation=false
